### ISSUE TITLE
Graphs not loading correctly

### ISSUE THREAD

**Issue by SkylerAusten** [brownplt/LTLTutor#24] opened 2024-05-19 20:26 UTC
User: sentience-blues

Graphs generated overlapping, and one answer's graph area was blank.

<img width="964" alt="image" src="https://github.com/brownplt/LTLTutor/assets/40815998/fcdf259d-98c0-4749-98ee-e5862c94d7d6">

**Comment by sidprasad** [comment] 2024-05-20 15:29
Duplicate of https://github.com/brownplt/LTLTutor/issues/13

**Closed by sidprasad** 2024-05-20 15:29 UTC
Labels: bug
